# Generated by Django 3.1.7 on 2021-06-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organic', '0002_best_seller_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='best_seller',
            name='new_tag',
            field=models.BooleanField(default=False),
        ),
    ]
