# Generated by Django 3.1.7 on 2021-06-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organic', '0003_best_seller_new_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best_seller',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='best_seller',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='best_seller',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='best_seller',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
