# Generated by Django 3.1.7 on 2021-06-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organic', '0004_auto_20210627_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best_seller',
            name='image',
            field=models.ImageField(upload_to='organic_product'),
        ),
    ]
