# Generated by Django 3.1.7 on 2021-06-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best_seller',
            name='image',
            field=models.ImageField(upload_to='digital_product'),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='image',
            field=models.ImageField(upload_to='digital_product'),
        ),
        migrations.AlterField(
            model_name='hot_deals',
            name='image',
            field=models.ImageField(upload_to='digital_product'),
        ),
        migrations.AlterField(
            model_name='microphones',
            name='image',
            field=models.ImageField(upload_to='digital_product'),
        ),
        migrations.AlterField(
            model_name='mp3_playes',
            name='image',
            field=models.ImageField(upload_to='digital_product'),
        ),
        migrations.AlterField(
            model_name='smart_home_appliances',
            name='image',
            field=models.ImageField(upload_to='digital_product'),
        ),
        migrations.AlterField(
            model_name='smart_remote_control',
            name='image',
            field=models.ImageField(upload_to='digital_product'),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='image',
            field=models.ImageField(upload_to='digital_product'),
        ),
        migrations.AlterField(
            model_name='wearable_devices',
            name='image',
            field=models.ImageField(upload_to='digital_product'),
        ),
    ]
