# Generated by Django 3.1.7 on 2021-06-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0002_auto_20210629_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wearable_devices',
        ),
    ]
