# Generated by Django 3.1.7 on 2021-06-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0003_delete_wearable_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='digital_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('image', models.ImageField(upload_to='digital_product')),
                ('design', models.TextField(default='STUDIO DESIGN')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_tag', models.BooleanField(default=False)),
                ('best_seller', models.BooleanField(default=False)),
                ('wearable_device', models.BooleanField(default=False)),
                ('smart_home_appliance', models.BooleanField(default=False)),
                ('smart_remote_control', models.BooleanField(default=False)),
                ('headphone', models.BooleanField(default=False)),
                ('speaker', models.BooleanField(default=False)),
                ('mp3_player', models.BooleanField(default=False)),
                ('microphone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wearable_devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('image', models.ImageField(upload_to='digital_product')),
                ('design', models.TextField(default='STUDIO DESIGN')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_tag', models.BooleanField(default=False)),
            ],
        ),
    ]
