# Generated by Django 3.1.7 on 2021-07-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0004_digital_products_wearable_devices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Best_seller',
        ),
        migrations.DeleteModel(
            name='Headphones',
        ),
        migrations.DeleteModel(
            name='Microphones',
        ),
        migrations.DeleteModel(
            name='Mp3_playes',
        ),
        migrations.DeleteModel(
            name='Smart_home_appliances',
        ),
        migrations.DeleteModel(
            name='Smart_remote_control',
        ),
        migrations.DeleteModel(
            name='Speakers',
        ),
        migrations.DeleteModel(
            name='Wearable_devices',
        ),
    ]
