# Generated by Django 3.1.7 on 2021-07-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0005_auto_20210702_1141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='digital_products',
            new_name='digital_prod',
        ),
    ]
