# Generated by Django 3.1.7 on 2021-07-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0006_auto_20210702_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microphones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('image', models.ImageField(upload_to='digital_product')),
                ('design', models.TextField(default='STUDIO DESIGN')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_tag', models.BooleanField(default=False)),
            ],
        ),
    ]
